//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//
//!	@file
//!	@SYMTestSuiteName			pbase-f32-sfsrv-publicapi-any
//!	@SYMScriptTestEnvironment		This test script requires a basic ROM.
//!	@SYMScriptAuthor 			Dmitri Trofimov
//!	@SYMScriptCreationDate			17/12/2006 
//!	@SYMScriptDescription			The test script contains API tests for the following functions of TVolumeInfo class:
//!	TVolumeInfo();


LOAD_SUITE	T_SfSrv
//DELAY		5000


START_TESTCASE 			PBASE-F32-VolumeInfo-PublicApi-0001
//! @SYMTestCaseID		PBASE-F32-VolumeInfo-PublicApi-0001
//! @SYMAPI			TVolumeInfo
//! @SYMTestCaseDesc		TVolumeInfo() test.
//!				Uses API elements: TVolumeInfo()
//! @SYMTestActions		1. Create TVolumeInfo object.
//!				2. Delete TVolumeInfo object.
//!
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		Critical
//! @SYMTestExpectedResults	Function does not leave nor panic.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_SfSrv	\base\PBASE-F32-VolumeInfo-PublicApi.ini
			CREATE_OBJECT	TVolumeInfo	TVolumeInfo1	
			COMMAND		TVolumeInfo1	new
			COMMAND		TVolumeInfo1	~
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-VolumeInfo-PublicApi-0001
