//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//
//! @file
//! @SYMTestSuiteName		PBASE-F32-RFS-Drives-PublicApi-RAM
//! @SYMScriptTestEnvironment	This test script requires a basic RAM.
//! @SYMScriptAuthor 		Anton Grober
//! @SYMScriptDescription	The test script contains API drives & volumes related tests for RFs functions that perform operations on a RAM (not removeable RAM drive).

LOAD_SUITE	T_Sfsrv


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1002
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1002
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		21/08/2006 
//! @SYMTestCaseDesc		Drive() function test. Passing exisiting drive index as parameter.
//!				Uses API elements: Drive()
//! @SYMTestActions		1. Call Connect().
//!				2. Call Drive() passing TDriveInfo reference as first parameter and RAM-drive as second parameter.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		Critical
//! @SYMTestExpectedResults	Function returns KErrNone and iType field of TDriveInfo indeicates a correct type.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND		RFs1	new		
		COMMAND		RFs1	Connect		
		COMMAND		RFs1	Drive		PBASE-F32-RFS-PublicApi-1002-001-Drive_command03
		COMMAND		RFs1	Close		
		COMMAND		RFs1	~		
	END_TEST_BLOCK
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1002


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1003
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1003
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		22/08/2006 
//! @SYMTestCaseDesc		Volume() and SetVolumeLabel() function test. Passing exisiting drive index as parameter.
//!				Uses API elements: Volume(), SetVolumeLabel().
//! @SYMTestActions		1. Call Connect().
//!				2. Saving volume label.
//!				3. Call SetVolumeLabel() passing "Test" as first parameter and the drive number as a second parameter.
//!				4. Call Volume() passing  TVolumeInfo reference as first parameter and the drive number as a second parameter.
//!				5. Restoring volume label.
//!				6. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		Critical
//! @SYMTestExpectedResults	Function SetVolumeLabel() returns KErrNone.  Function Volume() returns KErrNone and iName field of TVolumeInfo is "Test".
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND		RFs1	new		
		COMMAND		RFs1	Connect		
		COMMAND		RFs1	Volume		PBASE-F32-RFS-PublicApi-1003-001-Volume_command03
		COMMAND		RFs1	SetVolumeLabel		PBASE-F32-RFS-PublicApi-1003-001-SetVolumeLabel_command04
		COMMAND		RFs1	Volume		PBASE-F32-RFS-PublicApi-1003-001-Volume_command05
		COMMAND		RFs1	SetVolumeLabel		PBASE-F32-RFS-PublicApi-1003-001-SetVolumeLabel_command06
		COMMAND		RFs1	Close		
		COMMAND		RFs1	~		
	END_TEST_BLOCK
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1003


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1004
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1004
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		22/08/2006 
//! @SYMTestCaseDesc		SetSubst() and Subst() functions test. Passing exisiting drive index as second parameter and existing path to folder as second parameter.
//!				Uses API elements: Subst(), SetSubst().
//! @SYMTestActions		1. Call Connect().
//!				2. Call SetSubst() passing "\base\" as a first parameter and non-mounted valid drive's number as a drive number.
//!				3. Check that function returned KErrNone.	
//!				4. Call Subst() passing TDesC16 reference as first parameter and non-mounted valid drive's number as a drive number.
//!				5. Call SetSubst() passing ""(empty descriptor) as a first parameter and non-mounted valid drive's number as a drive number. This will unsubst the substed.
//!				6. Check that function returned KErrNone.
//!				7. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		Critical
//! @SYMTestExpectedResults	Function SetSubst() returns KErrNone. Functions Subst() returns "\base\" through TDesC16 reference and returns KErrNone.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND		RFs1	new		
		COMMAND		RFs1	Connect		
		COMMAND		RFs1	FileSystemName		PBASE-F32-RFS-PublicApi-1004-001-FileSystemName_command03
		COMMAND		RFs1	DismountFileSystem		PBASE-F32-RFS-PublicApi-1004-001-DismountFileSystem_command04
		COMMAND		RFs1	SetSubst		PBASE-F32-RFS-PublicApi-1004-001-SetSubst_command05
		COMMAND		RFs1	Subst		PBASE-F32-RFS-PublicApi-1004-001-Subst_command06
		COMMAND		RFs1	SetSubst		PBASE-F32-RFS-PublicApi-1004-001-SetSubst_command07
		COMMAND		RFs1	MountFileSystem		PBASE-F32-RFS-PublicApi-1004-001-MountFileSystem_command08
		COMMAND		RFs1	Close		
		COMMAND		RFs1	~		
	END_TEST_BLOCK
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1004


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1008
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1008
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		22/08/2006 
//! @SYMTestCaseDesc		CheckDisk() passing path with FAT filesystem.
//!				Uses API elements: CheckDisk().
//! @SYMTestActions		1. Call Connect().
//!				2. Call CheckDisk() passing drive with FAT filesystem as a drive number.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		Critical
//! @SYMTestExpectedResults	Function CheckDisk() returns KErrNone.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND		RFs1	new		
		COMMAND		RFs1	Connect		
		COMMAND		RFs1	CheckDisk		PBASE-F32-RFS-PublicApi-1008-001-CheckDisk_command03
		COMMAND		RFs1	Close		
		COMMAND		RFs1	~		
	END_TEST_BLOCK
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1008


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1009
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1009
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		22/08/2006 
//! @SYMTestCaseDesc		ScanDrive() passing path to drive with FAT filesystem.
//!				Uses API elements: ScanDrive();
//! @SYMTestActions		1. Call Connect().
//!				2. Call ScanDrive() passing drive's with FAT filesystem number as a drive number.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		Critical
//! @SYMTestExpectedResults	Function ScanDrive() returns KErrNone.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND		RFs1	new		
		COMMAND		RFs1	Connect		
		COMMAND		RFs1	ScanDrive		PBASE-F32-RFS-PublicApi-1009-001-ScanDrive_command03
		COMMAND		RFs1	Close		
		COMMAND		RFs1	~		
	END_TEST_BLOCK
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1009


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1010
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1010
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		22/08/2006 
//! @SYMTestCaseDesc		SetDriveName() and GetDriveName() tests. Passing existing drive as parameter and some descriptor as drive name or store for returned value.
//!						Uses API elements: GetDriveName(), SetDriveName();
//! @SYMTestActions		1. Call Connect().
//!				2. Saving drive name for restoring.
//!				3. Call SetDriveName() passing default drive's number as first parameter and "TEST" as second parameter.
//!				4. Call GetDriveName() passing default drive's number as first paramter and TDesC16 reference as second paramter.
//!				5. Restoring drive name.
//!				6. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		Critical
//! @SYMTestExpectedResults	Function SetDriveName() returns KErrNone. Function GetDriveName() returns "TEST" through a TDesC16 reference and returns KErrNone.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND		RFs1	new		
		COMMAND		RFs1	Connect		
		COMMAND		RFs1	GetDriveName		PBASE-F32-RFS-PublicApi-1010-001-GetDriveName_command03
		COMMAND		RFs1	SetDriveName		PBASE-F32-RFS-PublicApi-1010-001-SetDriveName_command04
		COMMAND		RFs1	GetDriveName		PBASE-F32-RFS-PublicApi-1010-001-GetDriveName_command05
		COMMAND		RFs1	SetDriveName		PBASE-F32-RFS-PublicApi-1010-001-SetDriveName_command06
		COMMAND		RFs1	Close		
		COMMAND		RFs1	~		
	END_TEST_BLOCK
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1010


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1013
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1013
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		22/08/2006 
//! @SYMTestCaseDesc		ReserveDriveSpace(), GetReserveAccess() and ReleaseReserveAccess() tests. Passing existing drive as first parameter and amount of space int bytes as second.
//!						Uses API elements: ReserveDriveSpace(), GetReserveAccess() and ReleaseReserveAccess().
//! @SYMTestActions		1. Call Connect().
//!				2. Call ReserveDriveSpace() passing 100(bytes) as first parameter and default drive's number as second parameter.	
//!				3. Call GetReserveAccess() passing default drive's number as parameter.
//!				4. Call ReleaseReserveAccess() passing default drive's number as parameter.
//!				5. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		Critical
//! @SYMTestExpectedResults	Function ReserveReserveAccess() returns KErrNone. Function GetReseveAccess() returns KErrNone. Function ReleaseReserveAccess() returns KErrNone.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND		RFs1	new		
		COMMAND		RFs1	Connect		
		COMMAND		RFs1	ReserveDriveSpace		PBASE-F32-RFS-PublicApi-1013-001-ReserveDriveSpace_command03
		COMMAND		RFs1	GetReserveAccess		PBASE-F32-RFS-PublicApi-1013-001-GetReserveAccess_command04
		COMMAND		RFs1	ReleaseReserveAccess		PBASE-F32-RFS-PublicApi-1013-001-ReleaseReserveAccess_command05
		COMMAND		RFs1	Close		
		COMMAND		RFs1	~		
	END_TEST_BLOCK
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1013


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1018
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1018
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		22/08/2006 
//! @SYMTestCaseDesc		Volume() function test. Passing non-mounted drive index as parameter.
//!				Uses API elements: Volume().
//! @SYMTestActions		1. Call Connect().
//!				2. Call Volume() passing  TVolumeInfo reference as first parameter and the non-mounted drive's number as a second parameter.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function Volume() returns KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new		
		COMMAND			RFs1	Connect		
		COMMAND			RFs1	FileSystemName		PBASE-F32-RFS-PublicApi-1018-001-FileSystemName_command03
		COMMAND			RFs1	DismountFileSystem		PBASE-F32-RFS-PublicApi-1018-001-DismountFileSystem_command04
		COMMAND	!Error=-18	RFs1	Volume		PBASE-F32-RFS-PublicApi-1018-001-Volume_command05
		COMMAND			RFs1	MountFileSystem		PBASE-F32-RFS-PublicApi-1018-001-MountFileSystem_command06
		COMMAND			RFs1	Close		
		COMMAND			RFs1	~		
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1018


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1020
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1020
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		02/10/2006 
//! @SYMTestCaseDesc		SetVolumeLabel() function test. Passing not mounted drive index as parameter.
//!				Uses API elements: SetVolumeLabel().
//! @SYMTestActions		1. Call Connect().
//!				2. Call SetVolumeLabel() passing  TVolumeInfo reference as first parameter and the non-mounted drive's number as a second parameter.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function SetVolumeLabel() returns KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new		
		COMMAND			RFs1	Connect		
		COMMAND			RFs1	FileSystemName		PBASE-F32-RFS-PublicApi-1020-001-FileSystemName_command03
		COMMAND			RFs1	DismountFileSystem		PBASE-F32-RFS-PublicApi-1020-001-DismountFileSystem_command04
		COMMAND	!Error=-18	RFs1	SetVolumeLabel		PBASE-F32-RFS-PublicApi-1020-001-SetVolumeLabel_command05
		COMMAND			RFs1	MountFileSystem		PBASE-F32-RFS-PublicApi-1020-001-MountFileSystem_command06
		COMMAND			RFs1	Close		
		COMMAND			RFs1	~		
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1020


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1022
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1022
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		02/10/2006 
//! @SYMTestCaseDesc		SetSubst() function test. Passing exisiting and mounted drive index as parameter.
//!				Uses API elements: SetSubst().
//! @SYMTestActions		1. Call Connect().
//!				2. Call SetSubst() passing some correct path descriptor as first parameter and some mounted drive as second.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function SetSubst() returns KErrGeneral.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new		
		COMMAND			RFs1	Connect		
		COMMAND	!Error=-2	RFs1	SetSubst		PBASE-F32-RFS-PublicApi-1022-001-SetSubst_command03
		COMMAND			RFs1	Close		
		COMMAND			RFs1	~		
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1022


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1023
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1023
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		02/10/2006 
//! @SYMTestCaseDesc		SetSubst() function test. Passing correct path as other parameter and incorrect drive index as parameter.
//!				Uses API elements: SetSubst().
//! @SYMTestActions		1. Call Connect().
//!				2. Call SetSubst() passing  descriptor with some icorrect path as first parameter and umounted drive number as second.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function SetSubst() returns KErrBadName.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new		
		COMMAND			RFs1	Connect		
		COMMAND	!Error=-28	RFs1	SetSubst		PBASE-F32-RFS-PublicApi-1023-001-SetSubst_command03
		COMMAND			RFs1	Close		
		COMMAND			RFs1	~		
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1023


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1024
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1024
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		02/10/2006 
//! @SYMTestCaseDesc		SetSubst() function test. Passing not mounted drive index as parameter and incorrect path as other parameter.
//!				Uses API elements: SetSubst().
//! @SYMTestActions		1. Call Connect().
//!				2. Call SetSubst() passing  descriptor with some incorrect path as first parameter and umounted drive number as second.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function SetSubst() returns KErrBadName.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new		
		COMMAND			RFs1	Connect		
		COMMAND			RFs1	FileSystemName		PBASE-F32-RFS-PublicApi-1024-001-FileSystemName_command03
		COMMAND			RFs1	DismountFileSystem		PBASE-F32-RFS-PublicApi-1024-001-DismountFileSystem_command04
		COMMAND	!Error=-28	RFs1	SetSubst		PBASE-F32-RFS-PublicApi-1024-001-SetSubst_command05
		COMMAND			RFs1	MountFileSystem		PBASE-F32-RFS-PublicApi-1024-001-MountFileSystem_command06
		COMMAND			RFs1	Close		
		COMMAND			RFs1	~		
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1024


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1031
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1031
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		22/08/2006 
//! @SYMTestCaseDesc		CheckDisk() test that passes a non-mounted drive number as a parameter.
//!				Uses API elements: CheckDisk()
//! @SYMTestActions		1. Call Connect().
//!				2. Call CheckDisk() passing non-mounted drive number as a parameter.	
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function CheckDisk() returns KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new		
		COMMAND			RFs1	Connect		
		COMMAND			RFs1	FileSystemName		PBASE-F32-RFS-PublicApi-1031-001-FileSystemName_command03
		COMMAND			RFs1	DismountFileSystem		PBASE-F32-RFS-PublicApi-1031-001-DismountFileSystem_command04
		COMMAND	!Error=-18	RFs1	CheckDisk		PBASE-F32-RFS-PublicApi-1031-001-CheckDisk_command05
		COMMAND			RFs1	MountFileSystem		PBASE-F32-RFS-PublicApi-1031-001-MountFileSystem_command06
		COMMAND			RFs1	Close		
		COMMAND			RFs1	~		
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1031


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1033
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1033
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		22/08/2006 
//! @SYMTestCaseDesc		ScanDrive() test that passes a non-mounted drive number as a parameter.
//!				Uses API elements: ScanDrive()
//! @SYMTestActions		1. Call Connect().
//!				2. Call ScanDrive() passing a non-mounted drive number as a parameter.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function ScanDrive() returns KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new		
		COMMAND			RFs1	Connect		
		COMMAND			RFs1	FileSystemName		PBASE-F32-RFS-PublicApi-1033-001-FileSystemName_command03
		COMMAND			RFs1	DismountFileSystem		PBASE-F32-RFS-PublicApi-1033-001-DismountFileSystem_command04
		COMMAND	!Error=-18	RFs1	ScanDrive		PBASE-F32-RFS-PublicApi-1033-001-ScanDrive_command05
		COMMAND			RFs1	MountFileSystem		PBASE-F32-RFS-PublicApi-1033-001-MountFileSystem_command06
		COMMAND			RFs1	Close		
		COMMAND			RFs1	~		
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1033


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1037
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1037
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		02/10/2006 
//! @SYMTestCaseDesc		LockDrive() function test. Passing not mounted drive index as parameter.
//!				Uses API elements: LockDrive().
//! @SYMTestActions		1. Call Connect().
//!				2. Call LockDrive() passing some nonmounted drive's number as drive number parameter.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function LockDrive() returns KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new		
		COMMAND			RFs1	Connect		
		COMMAND			RFs1	FileSystemName		PBASE-F32-RFS-PublicApi-1037-001-FileSystemName_command03
		COMMAND			RFs1	DismountFileSystem		PBASE-F32-RFS-PublicApi-1037-001-DismountFileSystem_command04
		COMMAND	!Error=-18	RFs1	LockDrive		PBASE-F32-RFS-PublicApi-1037-001-LockDrive_command05
		COMMAND			RFs1	MountFileSystem		PBASE-F32-RFS-PublicApi-1037-001-MountFileSystem_command06
		COMMAND			RFs1	Close		
		COMMAND			RFs1	~		
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1037


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1043
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1043
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		02/10/2006 
//! @SYMTestCaseDesc		ReserveDriveSpace() function test. Trying to reserve drive space again after getting access to it.
//!				Uses API elements: ReserveDriveSpace().
//! @SYMTestActions		1. Call Connect().
//!				2. Call ReserveDriveSpace() passing valid drive's number(RAM-drive's) as drive number parameter and 100(bytes) as amount of space to reserve.
//!				3. Call GetReserveAccess() with same drive's number(default drive's).
//!				4. Call ReserveDriveSpace() passing valid drive's number(RAM-drive's) as drive number parameter and 100 as amount of space to reserve.
//!				5. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function ReserveDriveSpace() returns KErrInUse.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT		RFs	RFs1
		COMMAND			RFs1	new		
		COMMAND			RFs1	Connect		
		COMMAND			RFs1	ReserveDriveSpace		PBASE-F32-RFS-PublicApi-1043-001-ReserveDriveSpace_command03
		COMMAND			RFs1	GetReserveAccess		PBASE-F32-RFS-PublicApi-1043-001-GetReserveAccess_command04
		COMMAND	!Error=-14	RFs1	ReserveDriveSpace		PBASE-F32-RFS-PublicApi-1043-001-ReserveDriveSpace_command05
		COMMAND			RFs1	Close		
		COMMAND			RFs1	~		
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1043


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1044
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1044
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		02/10/2006 
//! @SYMTestCaseDesc		ReserveDriveSpace() function test. Trying to reserve too much drive space.
//!				Uses API elements: ReserveDriveSpace().
//! @SYMTestActions		1. Call Connect().
//!				2. Call ReserveDriveSpace() passing valid drive's number(RAM-drive') as drive number parameter and 10000000000(in bytes and must be too big) as amount of space to reserve.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function ReserveDriveSpace() returns KErrArgument
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new		
		COMMAND			RFs1	Connect		
		COMMAND	!Error=-6	RFs1	ReserveDriveSpace		PBASE-F32-RFS-PublicApi-1044-001-ReserveDriveSpace_command03
		COMMAND			RFs1	Close		
		COMMAND			RFs1	~		
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1044


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1045
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1045
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		02/10/2006 
//! @SYMTestCaseDesc		GetReserveAccess() function test. Trying to get access without reserving any space before.
//!				Uses API elements: GetReserveAccess().
//! @SYMTestActions		1. Call Connect().
//!				2. Call GetReserveAccess() passing valid drive's number (RAM-drive') as drive number parameter.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function GetReserveAccess() returns KErrPremissionDenied.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new		
		COMMAND			RFs1	Connect		
		COMMAND	!Error=-46	RFs1	GetReserveAccess		PBASE-F32-RFS-PublicApi-1045-001-GetReserveAccess_command03
		COMMAND			RFs1	Close		
		COMMAND			RFs1	~		
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1045


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1053
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1053
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		22/08/2006 
//! @SYMTestCaseDesc		SetSubst() functions test. Passing existing path to folder as parameter. Using KDefaultDrive as drive parameter.
//!				Uses API elements: SetSubst().
//! @SYMTestActions		1. Call Connect().
//!				2. Call SetSubst() passing "\base\" as a first parameter. Testing with default drive.
//!				3. Call SetSubst() passing ""(empty descriptor) as a first parameter. This will unsubst the substed.
//!				4. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function SetSubst() returns KErrGeneral.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new		
		COMMAND			RFs1	Connect		
		COMMAND	!Error=-2	RFs1	SetSubst	PBASE-F32-RFS-PublicApi-1053-001-SetSubst_command03
		COMMAND	!Error=-2	RFs1	SetSubst	PBASE-F32-RFS-PublicApi-1053-001-SetSubst_command04
		COMMAND			RFs1	Close		
		COMMAND			RFs1	~		
	END_TEST_BLOCK
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1053


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1058
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1058
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		24/01/2007
//! @SYMTestCaseDesc		IsValidDrive() passing non-mounted drive as parameter.
//!				Uses API elements: IsValidDrive().
//! @SYMTestActions		1. Call IsValidDrive() passing non-mounted drive in range from EDriveC to EDriveZ.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function IsValidDrive() returns ETrue.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND		RFs1	new		
		COMMAND		RFs1	Connect		
		COMMAND		RFs1	FileSystemName		PBASE-F32-RFS-PublicApi-1058-001-FileSystemName_command03
		COMMAND		RFs1	DismountFileSystem		PBASE-F32-RFS-PublicApi-1058-001-DismountFileSystem_command04
		COMMAND		RFs1	IsValidDrive		PBASE-F32-RFS-PublicApi-1058-001-IsValidDrive_command05
		COMMAND		RFs1	MountFileSystem		PBASE-F32-RFS-PublicApi-1058-001-MountFileSystem_command06
		COMMAND		RFs1	Close		
		COMMAND		RFs1	~		
	END_TEST_BLOCK
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1058


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1062
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1062
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		22/08/2006 
//! @SYMTestCaseDesc		ReleaseReserveAccess() test that uses the function without previous call to ReserveDriveSpace(). 
//!				Uses API elements: ReleaseReserveAccess()
//! @SYMTestActions		1. Call Connect().
//!				2. Call ReleaseReserveAccess() passing RAM-drive's path as path parameter.	
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		Critical
//! @SYMTestExpectedResults	Function ReleaseReserveAccess() returns KErrNone.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND		RFs1	new		
		COMMAND		RFs1	Connect		
		COMMAND		RFs1	ReleaseReserveAccess		PBASE-F32-RFS-PublicApi-1062-001-ReleaseReserveAccess_command03
		COMMAND		RFs1	Close		
		COMMAND		RFs1	~		
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1062


START_TESTCASE			PBASE-F32-RFS-PublicApi-1063
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1063
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		22/08/2006 
//! @SYMTestCaseDesc		SetSubst() test. Passing some non-mounted drive index as parameter. Drive() test passing substed drive as parameter.
//!				Uses API elements: SetSubst(), Drive()
//! @SYMTestActions		1. Call Connect().
//!				2. Call SetSubst() with path '\base\' and non-mounted drive as parameter.
//!				3. Call Drive() and get through TDriveInfo object through the reference using the same drive as parameter.
//!				4. Call SetSubst() with empty path to unsubst the drive we have substed.
//!				5. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		Critical
//! @SYMTestExpectedResults	Function Drive() returns KErrNone and TDriveInfo object through the reference with KDriveAttSubsted attribute enabled.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND		RFs1	new		
		COMMAND		RFs1	Connect		
		COMMAND		RFs1	FileSystemName		PBASE-F32-RFS-PublicApi-1063-001-FileSystemName_command03
		COMMAND		RFs1	DismountFileSystem		PBASE-F32-RFS-PublicApi-1063-001-DismountFileSystem_command04
		COMMAND		RFs1	SetSubst		PBASE-F32-RFS-PublicApi-1063-001-SetSubst_command05
		COMMAND		RFs1	Drive		PBASE-F32-RFS-PublicApi-1063-001-Drive_command06
		COMMAND		RFs1	SetSubst		PBASE-F32-RFS-PublicApi-1063-001-SetSubst_command07
		COMMAND		RFs1	MountFileSystem		PBASE-F32-RFS-PublicApi-1063-001-MountFileSystem_command08
		COMMAND		RFs1	Close		
		COMMAND		RFs1	~		
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1063


START_TESTCASE			PBASE-F32-RFS-PublicApi-1065
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1065
//! @SYMAPI			RFs
//! @SYMCreationDate		22/08/2006 
//! @SYMTestCaseDesc		ErasePassword() test. Passing non-mounted drive's number as parameter .
//!				Uses API elements: ErasePassword()
//! @SYMTestActions		1. Call Connect().
//!				2. Call ErasePassword() passing not mounted drive's number.	
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function ErasePassword() returns KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new		
		COMMAND			RFs1	Connect		
		COMMAND			RFs1	FileSystemName		PBASE-F32-RFS-PublicApi-1065-001-FileSystemName_command03
		COMMAND			RFs1	DismountFileSystem		PBASE-F32-RFS-PublicApi-1065-001-DismountFileSystem_command04
		COMMAND	!Error=-18	RFs1	ErasePassword		PBASE-F32-RFS-PublicApi-1065-001-ErasePassword_command05
		COMMAND			RFs1	MountFileSystem		PBASE-F32-RFS-PublicApi-1065-001-MountFileSystem_command06
		COMMAND			RFs1	Close		
		COMMAND			RFs1	~		
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1065


START_TESTCASE			PBASE-F32-RFS-PublicApi-1070
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1070
//! @SYMAPI			RFs
//! @SYMCreationDate		22/08/2006 
//! @SYMTestCaseDesc		ClearPassword() test. Passing non-mounted drive's number as parameter.
//!				Uses API elements: ClearPassword()
//! @SYMTestActions		1. Call Connect().
//!				2. Call ClearPassword() passing not mounted drive's number and 'test' as password.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function ClearPassword() returns KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new		
		COMMAND			RFs1	Connect		
		COMMAND			RFs1	FileSystemName		PBASE-F32-RFS-PublicApi-1070-001-FileSystemName_command03
		COMMAND			RFs1	DismountFileSystem		PBASE-F32-RFS-PublicApi-1070-001-DismountFileSystem_command04
		COMMAND	!Error=-18	RFs1	ClearPassword		PBASE-F32-RFS-PublicApi-1070-001-ClearPassword_command05
		COMMAND			RFs1	MountFileSystem		PBASE-F32-RFS-PublicApi-1070-001-MountFileSystem_command06
		COMMAND			RFs1	Close		
		COMMAND			RFs1	~		
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1070


START_TESTCASE			PBASE-F32-RFS-PublicApi-1075
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1075
//! @SYMAPI			RFs
//! @SYMCreationDate		22/08/2006 
//! @SYMTestCaseDesc		UnlockDrive() test. Passing non-mounted drive's number as parameter.
//!				Uses API elements: UnlockDrive()
//! @SYMTestActions		1. Call Connect().
//!				2. Call UnlockDrive() passing not mounted drive's number and 'test' as password.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function UnlockDrive() returns KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new		
		COMMAND			RFs1	Connect		
		COMMAND			RFs1	FileSystemName		PBASE-F32-RFS-PublicApi-1075-001-FileSystemName_command03
		COMMAND			RFs1	DismountFileSystem		PBASE-F32-RFS-PublicApi-1075-001-DismountFileSystem_command04
		COMMAND	!Error=-18	RFs1	UnlockDrive		PBASE-F32-RFS-PublicApi-1075-001-UnlockDrive_command05
		COMMAND			RFs1	MountFileSystem		PBASE-F32-RFS-PublicApi-1075-001-MountFileSystem_command06
		COMMAND			RFs1	Close		
		COMMAND			RFs1	~		
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1075


START_TESTCASE			PBASE-F32-RFS-PublicApi-1078
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1078
//! @SYMAPI			RFs
//! @SYMCreationDate		08/02/2007 
//! @SYMTestCaseDesc		ReserveDriveSpace() test. Testing with non-mounted drive.
//!				Uses API elements: ReserveDriveSpace()
//! @SYMTestActions		1. Call Connect().
//!				2. Call ReserveDriveSpace() passing non-mounted drive's number and 100(bytes) to reserve.	
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function ReserveDriveSpace() returns KErrNotReady.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new		
		COMMAND			RFs1	Connect		
		COMMAND			RFs1	FileSystemName		PBASE-F32-RFS-PublicApi-1078-001-FileSystemName_command03
		COMMAND			RFs1	DismountFileSystem		PBASE-F32-RFS-PublicApi-1078-001-DismountFileSystem_command04
		COMMAND	!Error=-18	RFs1	ReserveDriveSpace		PBASE-F32-RFS-PublicApi-1078-001-ReserveDriveSpace_command05
		COMMAND			RFs1	MountFileSystem		PBASE-F32-RFS-PublicApi-1078-001-MountFileSystem_command06
		COMMAND			RFs1	Close		
		COMMAND			RFs1	~		
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1078


START_TESTCASE			PBASE-F32-RFS-PublicApi-1079
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1079
//! @SYMAPI			RFs
//! @SYMCreationDate		08/02/2007 
//! @SYMTestCaseDesc		GetReserveAccess() test. Testing with non-mounted drive.
//!				Uses API elements: GetReserveAccess()
//! @SYMTestActions		1. Call Connect().
//!				2. Call GetReserveAccess() passing non-mounted drive's number.	
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function GetReserveAccess() returns KErrPermissionDenied.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new		
		COMMAND			RFs1	Connect		
		COMMAND			RFs1	FileSystemName		PBASE-F32-RFS-PublicApi-1079-001-FileSystemName_command03
		COMMAND			RFs1	DismountFileSystem		PBASE-F32-RFS-PublicApi-1079-001-DismountFileSystem_command04
		COMMAND	!Error=-46	RFs1	GetReserveAccess		PBASE-F32-RFS-PublicApi-1079-001-GetReserveAccess_command05
		COMMAND			RFs1	MountFileSystem		PBASE-F32-RFS-PublicApi-1079-001-MountFileSystem_command06
		COMMAND			RFs1	Close		
		COMMAND			RFs1	~		
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1079


START_TESTCASE			PBASE-F32-RFS-PublicApi-1080
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1080
//! @SYMAPI			RFs
//! @SYMCreationDate		08/02/2007 
//! @SYMTestCaseDesc		ReleaseReserveAccess() test.Testing with non-mounted drive.
//!				Uses API elements: ReleaseReserveAccess()
//! @SYMTestActions		1. Call Connect().
//!				2. Call ReleaseReserveAccess() passing non-mounted drive's number.	
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function ReleaseReserveAccess() returns KErrNone.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND		RFs1	new		
		COMMAND		RFs1	Connect		
		COMMAND		RFs1	FileSystemName		PBASE-F32-RFS-PublicApi-1080-001-FileSystemName_command03
		COMMAND		RFs1	DismountFileSystem		PBASE-F32-RFS-PublicApi-1080-001-DismountFileSystem_command04
		COMMAND		RFs1	ReleaseReserveAccess		PBASE-F32-RFS-PublicApi-1080-001-ReleaseReserveAccess_command05
		COMMAND		RFs1	MountFileSystem		PBASE-F32-RFS-PublicApi-1080-001-MountFileSystem_command06
		COMMAND		RFs1	Close		
		COMMAND		RFs1	~		
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1080

START_TESTCASE 			PBASE-F32-RFS-PublicApi-1027
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1027
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		02/10/2006 
//! @SYMTestCaseDesc		GetMediaSerialNumber() function test. Passing substed drive's index as parameter.
//!				Uses API elements: GetMediaSerialNumber().
//! @SYMTestActions		1. Call Connect().
//!				2. Call Subst() passing empty drive suitable for substing as drive number and "<DRIVE>:\base\" as path where <DRIVE> is a test drive.
//!				3. Call GetMediaSerialNumber() passing  descriptor reference as first parameter and substed drive number as second.
//!				4. Call Subst passing empty drive suitable for substing as drive number and ""(empty descriptor) to unsubst drive.
//!				5. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function GetMediaSerialNumber() returns KErrNotSupported
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new		
		COMMAND			RFs1	Connect		
		COMMAND			RFs1	FileSystemName		PBASE-F32-RFS-PublicApi-1027-001-FileSystemName_command03
		COMMAND			RFs1	DismountFileSystem		PBASE-F32-RFS-PublicApi-1027-001-DismountFileSystem_command04
		COMMAND			RFs1	SetSubst		PBASE-F32-RFS-PublicApi-1027-001-SetSubst_command05
		COMMAND	!Error=-5	RFs1	GetMediaSerialNumber		PBASE-F32-RFS-PublicApi-1027-001-GetMediaSerialNumber_command06
		COMMAND			RFs1	SetSubst		PBASE-F32-RFS-PublicApi-1027-001-SetSubst_command07
		COMMAND			RFs1	MountFileSystem		PBASE-F32-RFS-PublicApi-1027-001-MountFileSystem_command08
		COMMAND			RFs1	Close		
		COMMAND			RFs1	~		
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1027

START_TESTCASE 			PBASE-F32-RFS-PublicApi-1086
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1086
//! @SYMAPI			RFs
//! @SYMTestCaseDesc		Function VolumeIOParam() test with non mounted drive.
//!				Uses API elements: VolumeIOParam().
//! @SYMTestActions		1. Call Connect() method.
//!				2. Call VolumeIOParam() passing the drive number where is not mounted file system as argument.
//!				3. Call Close() method.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		Critical
//! @SYMTestExpectedResults	Return KErrNotReady (-18).
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-RAM.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new		
		COMMAND			RFs1	Connect		
		COMMAND			RFs1	FileSystemName		PBASE-F32-RFS-PublicApi-1086-001-FileSystemName_command03
		COMMAND			RFs1	DismountFileSystem	PBASE-F32-RFS-PublicApi-1086-001-DismountFileSystem_command04
		COMMAND	!Error=-18	RFs1	VolumeIOParam		PBASE-F32-RFS-PublicApi-1086-001-VolumeIOParam_command05
		COMMAND			RFs1	MountFileSystem		PBASE-F32-RFS-PublicApi-1086-001-MountFileSystem_command06
		COMMAND			RFs1	Close		
		COMMAND			RFs1	~		
	END_TEST_BLOCK
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1086


