//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//
//! @file
//! @SYMTestSuiteName		pbase-f32-sfsrv-publicapi-os
//! @SYMScriptTestEnvironment	This test script requires a basic ROM.
//! @SYMScriptAuthor 		Jaanus Randveer
//! @SYMScriptCreationDate		18/19/2007
//! @SYMScriptDescription		The test script contains API tests for the following functions of CFileMan class:
//!	TInt BytesTransferredByCopyStep()


LOAD_SUITE	T_SfSrv

START_TESTCASE			PBASE-F32-FileMan-PublicApi-2165
//! @SYMTestCaseID		PBASE-F32-FileMan-PublicApi-2165
//! @SYMAPI			CFileBase
//! @SYMTestCaseDesc		Function  BytesTransferredByCopyStep() test.
//!											Check that function BytesTransferredByCopyStep() was called more that one time during Copy processs.
//! 				Uses API elements: NewL(), Copy(), Delete();
//! @SYMTestActions		1.Create a RFs session and call it's Connect() function.
//!				2.Call CFileMan::NewL(RFs &aFs) and connected file server session as parameter.
//!				3.Call CFileMan::Copy(const TDesC &anOld, const TDesC &aNew, TUint aSwitch=EOverWrite),
//!				  and {TestPath}fileman\1mb as first parameter, 
//!				  and {TestPath}fileman\Copy\ as second parameter,
//!					and aSwitch = 0.
//!				4.Check that in history for NotifyFileManOperation no record with total size of file.
//!				5.Check that in history for NotifyFileManOperation total size of transfered bytes equals to to size of transfered file.
//!				6.Call CFileMan::Delete(const TDesC &aName, TUint aSwitch=0), 
//!				  and {TestPath}fileman\Copy\* as parameter.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		Critical
//! @SYMTestExpectedResults Second and third copy calls return KErrAlreadyExists.
//! @SYMTestType		CIT
	START_TEST_BLOCK	50	T_SfSrv	\base\PBASE-F32-FileMan-PublicApi.ini 
		CREATE_OBJECT	RFs				RFs1
		CREATE_OBJECT	CFileMan	CFileMan1
		COMMAND		RFs1			new
		COMMAND		RFs1			Connect
		COMMAND		RFs1			MkDirAll		PBASE-F32-FileMan-PublicApi-2165-001-MkDirAll_command001
		COMMAND		CFileMan1	NewL				PBASE-F32-FileMan-PublicApi-NewL
		COMMAND		CFileMan1	SetObserver
		COMMAND		CFileMan1	Copy				PBASE-F32-FileMan-PublicApi-2165-001-Copy_command002
		COMMAND		CFileMan1	BytesTransferredByCopyStep				PBASE-F32-FileMan-PublicApi-2165-001-BytesTransferredByCopyStep_command003
		COMMAND		CFileMan1	Delete			PBASE-F32-FileMan-PublicApi-2165-001-Delete_command004
		COMMAND		CFileMan1	RmDir				PBASE-F32-FileMan-PublicApi-2165-001-RmDir_command005
		COMMAND		CFileMan1	~
		COMMAND		RFs1			~		
	END_TEST_BLOCK	
END_TESTCASE			PBASE-F32-FileMan-PublicApi-2165