//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//
//! @file
//! @SYMTestSuiteName		PBASE-F32-RFS-Drives-PublicApi-ANY
//! @SYMScriptTestEnvironment	This test script requires a basic ROM.
//! @SYMScriptAuthor 		Anton Grober
//! @SYMScriptDescription	The test script contains API drives & volumes related tests for RFs functions that don't depend on any special type of test drive.

LOAD_SUITE	T_Sfsrv


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1001
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1001
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober
//! @SYMCreationDate		21/08/2006
//! @SYMTestCaseDesc		DriveList() test.
//!				Uses API elements: DriveList().
//! @SYMTestActions		1. Call Connect().
//!				2. Call DriveList() passing TDriveList as a reference.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		Critical
//! @SYMTestExpectedResults	DriveList() completes with KErrNone and returns at least C and Z drives.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND		RFs1	new
		COMMAND		RFs1	Connect
		COMMAND		RFs1	DriveList		PBASE-F32-RFS-PublicApi-1001-001-DriveList_command03
		COMMAND		RFs1	Close
		COMMAND		RFs1	~
	END_TEST_BLOCK
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1001


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1007
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1007
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober
//! @SYMCreationDate		22/08/2006
//! @SYMTestCaseDesc		CharToDrive() and DriveToChar() tests. Passing exisiting drive and character representing that drive in both cases.
//!				Uses API elements: CharToDrive(), DriveToChar()
//! @SYMTestActions		1. Call CharToDrive() passing 'X' as first parameter and TInt reference as second parameter.
//!				2. Call DriveToChar() passing EdriveX as first parameter and TChar reference as second parameter.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		Critical
//! @SYMTestExpectedResults	Function CharToDrive() returns EDriveX through reference parameter and returns KErrNone. Fucntion DriveToChar returns 'X' through reference parameter and returns KErrNone.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND		RFs1	CharToDrive		PBASE-F32-RFS-PublicApi-1007-001-CharToDrive_command01
		COMMAND		RFs1	DriveToChar		PBASE-F32-RFS-PublicApi-1007-001-DriveToChar_command02
		COMMAND		RFs1	~
	END_TEST_BLOCK
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1007


START_TESTCASE			PBASE-F32-RFS-PublicApi-1015
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1015
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober
//! @SYMCreationDate		2/10/2006
//! @SYMTestCaseDesc		Drive() negative test. Passing incorrect drive number as parameter.
//!				Uses API elements: Drive().
//! @SYMTestActions		1. Call Connect().
//!				2. Call Drive() passing TDriveInfo reference as first parameter and non-existent drive number.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function Drive() returns KErrBadName.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new
		COMMAND			RFs1	Connect
		COMMAND	!Error=-28	RFs1	Drive		PBASE-F32-RFS-PublicApi-1015-001-Drive_command03
		COMMAND			RFs1	Close
		COMMAND			RFs1	~
	END_TEST_BLOCK
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1015


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1017
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1017
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober
//! @SYMCreationDate		2/10/2006
//! @SYMTestCaseDesc		Volume(). Passing non-exisiting drive index as parameter.
//!				Uses API elements: Volume().
//! @SYMTestActions		1. Call Connect().
//!				2. Call Volume() passing  TVolumeInfo reference as first parameter and the non-existing drive number as a second parameter.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function Volume() returns KErrBadName.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new
		COMMAND			RFs1	Connect
		COMMAND	!Error=-28	RFs1	Volume		PBASE-F32-RFS-PublicApi-1017-001-Volume_command03
		COMMAND			RFs1	Close
		COMMAND			RFs1	~
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1017


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1019
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1019
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober
//! @SYMCreationDate		02/10/2006
//! @SYMTestCaseDesc		SetVolumeLabel() function test. Passing incorrect drive index as parameter.
//!				Uses API elements: SetVolumeLabel().
//! @SYMTestActions		1. Call Connect().
//!				2. Call SetVolumelabel() passing incorrect drive index as a parameter.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function SetVolumeLabel() returns KErrBadName.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new
		COMMAND			RFs1	Connect
		COMMAND	!Error=-28	RFs1	SetVolumeLabel		PBASE-F32-RFS-PublicApi-1019-001-SetVolumeLabel_command03
		COMMAND			RFs1	Close
		COMMAND			RFs1	~
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1019


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1025
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1025
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober
//! @SYMCreationDate		02/10/2006
//! @SYMTestCaseDesc		Subst() function test. Passing incorrect drive number as parameter.
//!				Uses API elements: Subst().
//! @SYMTestActions		1. Call Connect().
//!				2. Call Subst() passing incorrect drive number as parameter.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function Subst() returns KErrBadName.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new
		COMMAND			RFs1	Connect
		COMMAND	!Error=-28	RFs1	Subst		PBASE-F32-RFS-PublicApi-1025-001-Subst_command03
		COMMAND			RFs1	Close
		COMMAND			RFs1	~
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1025


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1028
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1028
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober
//! @SYMCreationDate		22/08/2006
//! @SYMTestCaseDesc		CharToDrive() tests. Passing incorrect character as parameter.
//!				Uses API elements: CharToDrive().
//! @SYMTestActions		1. Call Connect().
//!				2. Call CharToDrive() passing incorrect character as first parameter and TInt reference as second parameter.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function CharToDrive() returns KErrArgument.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND	!Error=-6	RFs1	CharToDrive		PBASE-F32-RFS-PublicApi-1028-001-CharToDrive_command01
		COMMAND			RFs1	~
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1028


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1029
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1029
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober
//! @SYMCreationDate		22/08/2006
//! @SYMTestCaseDesc		DriveToChar() tests. Passing incorrect number as parameter.
//!				Uses API elements: DriveToChar()
//!				1. Call DriveToChar() passing bad drive index as first parameter and TChar reference as second parameter.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function DriveToChar() returns KErrArgument.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND	!Error=-6	RFs1	DriveToChar		PBASE-F32-RFS-PublicApi-1029-001-DriveToChar_command01
		COMMAND			RFs1	~
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1029


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1030
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1030
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober
//! @SYMCreationDate		22/08/2006
//! @SYMTestCaseDesc		CheckDisk() test. Passing invalid drive path as a parameter.
//!				Uses API elements: CheckDisk(), SetSessionPath()
//! @SYMTestActions		1. Call Connect().
//!				2. Call SetSessionPath() passing RAMDriveTestPath value as a parameter to set RAM drive as a default drive
//!				3. Call CheckDisk() passing "ThisIsNotADrivePath" value instead of a drive path.
//!				4. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	CheckDisk() returns KErrNone, as it checks the default drive set by SetSessionPath when the drive
//!                              path is invalid.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new
		COMMAND			RFs1	Connect
		COMMAND			RFs1	SetSessionPath		PBASE-F32-RFS-PublicApi-1030-001-SetSessionPath_command02
		COMMAND			RFs1	CheckDisk		PBASE-F32-RFS-PublicApi-1030-001-CheckDisk_command03
		COMMAND			RFs1	Close
		COMMAND			RFs1	~
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1030


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1032
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1032
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober
//! @SYMCreationDate		22/08/2006
//! @SYMTestCaseDesc		ScanDrive() test. Passing not a drive path as a parameter.
//!				Uses API elements: ScanDrive()
//! @SYMTestActions		1. Call Connect().
//!				2. Call ScanDrive() passing "ThisIsNotADrivePath" value instead of a drive path.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function ScanDrive() returns KErrInUse(-14).
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new
		COMMAND			RFs1	Connect
		COMMAND	!Error=-14	RFs1	ScanDrive		PBASE-F32-RFS-PublicApi-1032-001-ScanDrive_command03
		COMMAND			RFs1	Close
		COMMAND			RFs1	~
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1032


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1034
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1034
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober
//! @SYMCreationDate		02/10/2006
//! @SYMTestCaseDesc		SetDriveName() function test. Passing incorrect drive number as parameter.
//!				Uses API elements: SetDriveName().
//! @SYMTestActions		1. Call Connect().
//!				2. Call SetDriveName() passing incorrect drive number as first parameter and descriptor reference as second.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function SetDriveName() returns KErrBadName.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new
		COMMAND			RFs1	Connect
		COMMAND	!Error=-28	RFs1	SetDriveName		PBASE-F32-RFS-PublicApi-1034-001-SetDriveName_command03
		COMMAND			RFs1	Close
		COMMAND			RFs1	~
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1034


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1035
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1035
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober
//! @SYMCreationDate		02/10/2006
//! @SYMTestCaseDesc		GetDriveName() function test. Passing incorect drive number as parameter.
//!				Uses API elements: GetDriveName().
//! @SYMTestActions		1. Call Connect().
//!				2. Call GetDriveName() passing incorrect drive number as first parameter and descriptor reference as second.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function GetDriveName() returns KErrBadName.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new
		COMMAND			RFs1	Connect
		COMMAND	!Error=-28	RFs1	GetDriveName		PBASE-F32-RFS-PublicApi-1035-001-GetDriveName_command03
		COMMAND			RFs1	Close
		COMMAND			RFs1	~
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1035


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1046
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1046
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober
//! @SYMCreationDate		02/10/2006
//! @SYMTestCaseDesc		GetReserveAccess() passing invalid drive's number as drive number parameter.
//!				Uses API elements: GetReserveAccess().
//! @SYMTestActions		1. Call Connect().
//!				2. Call GetReserveAccess() passing invalid drive's number as drive number parameter.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function GetReserveAccess() returns KErrBadName.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new
		COMMAND			RFs1	Connect
		COMMAND	!Error=-28	RFs1	GetReserveAccess		PBASE-F32-RFS-PublicApi-1046-001-GetReserveAccess_command03
		COMMAND			RFs1	Close
		COMMAND			RFs1	~
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1046


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1047
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1047
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober
//! @SYMCreationDate		02/10/2006
//! @SYMTestCaseDesc		ReleaseReserveAccess() function test. Passing invalid drive number as parameter.
//!				Uses API elements: ReleaseReserveAccess().
//! @SYMTestActions		1. Call Connect().
//!				2. Call ReleaseReserveAccess() passing invalid drive's number as drive number parameter.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function ReleaseReserveAccess() returns KErrBadName.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new
		COMMAND			RFs1	Connect
		COMMAND	!Error=-28	RFs1	ReleaseReserveAccess		PBASE-F32-RFS-PublicApi-1047-001-ReleaseReserveAccess_command03
		COMMAND			RFs1	Close
		COMMAND			RFs1	~
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1047


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1038
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1038
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober
//! @SYMCreationDate		02/10/2006
//! @SYMTestCaseDesc		LockDrive() function test. Passing invalid drive index as parameter.
//!				Uses API elements: LockDrive().
//! @SYMTestActions		1. Call Connect().
//!				2. Call LockDrive() passing some invalid drive's number as drive number parameter.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function LockDrive() returns KErrBadName.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new
		COMMAND			RFs1	Connect
		COMMAND	!Error=-28	RFs1	LockDrive		PBASE-F32-RFS-PublicApi-1038-001-LockDrive_command03
		COMMAND			RFs1	Close
		COMMAND			RFs1	~
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1038


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1050
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1050
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober
//! @SYMCreationDate		20/12/2006
//! @SYMTestCaseDesc		Drive() function test with KDefaultDrive as paramteter.
//!				Uses API elements: Drive().
//! @SYMTestActions		1. Call Connect().
//!				2. Call Drive() with TDriveInfo parameter as a refernce.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		Critical
//! @SYMTestExpectedResults	Function Drive() returns KErrNone.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND		RFs1	new
		COMMAND		RFs1	Connect
		COMMAND		RFs1	Drive
		COMMAND		RFs1	Close
		COMMAND		RFs1	~
	END_TEST_BLOCK
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1050


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1051
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1051
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober
//! @SYMCreationDate		4/01/2007
//! @SYMTestCaseDesc		Volume() function test with KDefaultDrive as paramteter.
//!				Uses API elements: Volume().
//! @SYMTestActions		1. Call Connect().
//!				2. Call Volume() with TVolumeInfo parameter as a refernce.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		Critical
//! @SYMTestExpectedResults	Function Volume() returns KErrNone.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND		RFs1	new
		COMMAND		RFs1	Connect
		COMMAND		RFs1	Volume
		COMMAND		RFs1	Close
		COMMAND		RFs1	~
	END_TEST_BLOCK
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1051


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1059
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1059
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober
//! @SYMCreationDate		24/01/2007
//! @SYMTestCaseDesc		IsValidDrive() passing bad drive index.
//!				Uses API elements: IsValidDrive().
//! @SYMTestActions		1. Call IsValidDrive() passing  bad drive index.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function IsValidDrive() returns EFalse.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND		RFs1	new
		COMMAND		RFs1	IsValidDrive		PBASE-F32-RFS-PublicApi-1059-001-IsValidDrive_command02
		COMMAND		RFs1	~
	END_TEST_BLOCK
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1059


START_TESTCASE			PBASE-F32-RFS-PublicApi-1064
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1064
//! @SYMAPI			RFs
//! @SYMCreationDate		22/08/2006
//! @SYMTestCaseDesc		ErasePassword() test. Passing invalid drive's number.
//!				Uses API elements: ErasePassword()
//! @SYMTestActions		1. Call Connect().
//!				2. Call ErasePassword() passing invalid drive's number.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function ErasePassword() returns KErrBadName.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new
		COMMAND			RFs1	Connect
		COMMAND	!Error=-28	RFs1	ErasePassword		PBASE-F32-RFS-PublicApi-1064-001-ErasePassword_command03
		COMMAND			RFs1	Close
		COMMAND			RFs1	~
	END_TEST_BLOCK
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1064


START_TESTCASE			PBASE-F32-RFS-PublicApi-1069
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1069
//! @SYMAPI			RFs
//! @SYMCreationDate		22/08/2006
//! @SYMTestCaseDesc		ClearPassword() test. Passing invalid drive's number.
//!				Uses API elements: ClearPassword()
//! @SYMTestActions		1. Call Connect().
//!				2. Call ClearPassword() passing invalid drive's number.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function ErasePassword() returns KErrBadName.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new
		COMMAND			RFs1	Connect
		COMMAND	!Error=-28	RFs1	ClearPassword		PBASE-F32-RFS-PublicApi-1069-001-ClearPassword_command03
		COMMAND			RFs1	Close
		COMMAND			RFs1	~
	END_TEST_BLOCK
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1069


START_TESTCASE			PBASE-F32-RFS-PublicApi-1074
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1074
//! @SYMAPI			RFs
//! @SYMCreationDate		22/08/2006
//! @SYMTestCaseDesc		UnlockDrive() test. Passing invalid drive's number.
//!				Uses API elements: UnlockDrive()
//! @SYMTestActions		1. Call Connect().
//!				2. Call UnlockDrive() passing invalid drive's number and some password.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function UnlockDrive() returns KErrBadName.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new
		COMMAND			RFs1	Connect
		COMMAND	!Error=-28	RFs1	UnlockDrive		PBASE-F32-RFS-PublicApi-1074-001-UnlockDrive_command03
		COMMAND			RFs1	Close
		COMMAND			RFs1	~
	END_TEST_BLOCK
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1074


START_TESTCASE			PBASE-F32-RFS-PublicApi-1084
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1084
//! @SYMAPI			RFs
//! @SYMCreationDate		08/02/2007
//! @SYMTestCaseDesc		DriveToChar() test with a KDefaultDrive as a drive number.
//!				Uses API elements: DriveToChar()
//! @SYMTestActions		1. Call DriveToChar() passing a KDefaultDrive (= KMaxTInt = 2147483647) as a drive number.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function DriveToChar() returns KErrNone.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini
		CREATE_OBJECT	RFs	RFs1
		COMMAND		RFs1	DriveToChar		PBASE-F32-RFS-PublicApi-1084-001-DriveToChar_command01
		COMMAND		RFs1	~
	END_TEST_BLOCK
END_TESTCASE			PBASE-F32-RFS-PublicApi-1084

START_TESTCASE 			PBASE-F32-RFS-PublicApi-1014
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1014
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		25/09/2006 
//! @SYMTestCaseDesc		GetSystemDrive() test.
//!				Uses API elements: GetSystemDrive().
//! @SYMTestActions		1. Call GetSystemDrive().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		Critical
//! @SYMTestExpectedResults	Function GetSystemDrive() returns default drive's number in case system configuration is default.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND		RFs1	GetSystemDrive		PBASE-F32-RFS-PublicApi-1014-001-GetSystemDrive_command01
		COMMAND		RFs1	~		
	END_TEST_BLOCK	
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1014


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1026
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1026
//! @SYMAPI			RFs
//! @SYMAuthor			Anton Grober 
//! @SYMCreationDate		02/10/2006 
//! @SYMTestCaseDesc		GetMediaSerialNumber() function test. Passing incorrect drive number as parameter.
//!				Uses API elements: GetMediaSerialNumber().
//! @SYMTestActions		1. Call Connect().
//!				2. Call GetMediaSerialNumber() passing  descriptor reference as first parameter and incorrect drive number as second.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		High
//! @SYMTestExpectedResults	Function GetMediaSerialNumber() returns KErrBadName.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new
		COMMAND			RFs1	Connect
		COMMAND	!Error=-28	RFs1	GetMediaSerialNumber		PBASE-F32-RFS-PublicApi-1026-001-GetMediaSerialNumber_command03
		COMMAND			RFs1	Close
		COMMAND			RFs1	~		
	END_TEST_BLOCK	
END_TESTCASE			PBASE-F32-RFS-PublicApi-1026


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1081
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1081
//! @SYMAPI			RFs
//! @SYMAuthor			Oleg Kuznetsov
//! @SYMCreationDate		02/03/2007
//! @SYMTestCaseDesc		Functions GetSystemDriveChar() test.
//!				Uses API elements: GetSystemDriveChar().
//! @SYMTestActions		1. Call Connect().
//!				2. Call GetSystemDriveChar().
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		Critical
//! @SYMTestExpectedResults	GetSystemDriveChar() completes with KErrNone and returns 'C' char.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND		RFs1	new
		COMMAND		RFs1	Connect
		COMMAND		RFs1	GetSystemDriveChar		PBASE-F32-RFS-PublicApi-1081-001-GetSystemDriveChar_command03
		COMMAND		RFs1	Close
		COMMAND		RFs1	~		
	END_TEST_BLOCK	
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1081


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1082
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1082
//! @SYMAPI			RFs
//! @SYMAuthor			Oleg Kuznetsov
//! @SYMCreationDate		02/03/2007
//! @SYMTestCaseDesc		Functions VolumeIOParam() test with default drive letter.
//!				Uses API elements: VolumeIOParam().
//! @SYMTestActions		1. Call Connect().
//!				2. Call VolumeIOParam() passing default drive as argument.
//!				3. Call Close().
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		Critical
//! @SYMTestExpectedResults	VolumeIOParam() completes with KErrNone and returns volume IO parameter information.
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND		RFs1	new
		COMMAND		RFs1	Connect
		COMMAND		RFs1	VolumeIOParam		PBASE-F32-RFS-PublicApi-1082-001-VolumeIOParam_command03
		COMMAND		RFs1	Close
		COMMAND		RFs1	~		
	END_TEST_BLOCK	
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1082


START_TESTCASE 			PBASE-F32-RFS-PublicApi-1085
//! @SYMTestCaseID		PBASE-F32-RFS-PublicApi-1085
//! @SYMAPI			RFs
//! @SYMTestCaseDesc		Function VolumeIOParam() test with negative drive letter.
//!				Uses API elements: VolumeIOParam().
//! @SYMTestActions		1. Call Connect() method.
//!				2. Call VolumeIOParam() passing the negative drive number as argument.
//!				3. Call Close() method.
//! @SYMTestStatus		Implemented
//! @SYMTestPriority		Critical
//! @SYMTestExpectedResults	Return KErrArgument (-6).
//! @SYMTestType		CIT
	START_TEST_BLOCK	100	T_Sfsrv	\base\PBASE-F32-RFS-Drives-PublicApi-ANY.ini 
		CREATE_OBJECT	RFs	RFs1
		COMMAND			RFs1	new
		COMMAND			RFs1	Connect
		COMMAND	!Error=-6	RFs1	VolumeIOParam		PBASE-F32-RFS-PublicApi-1085-001-VolumeIOParam_command03
		COMMAND			RFs1	Close
		COMMAND			RFs1	~		
	END_TEST_BLOCK	
END_TESTCASE 			PBASE-F32-RFS-PublicApi-1085

