//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//
//! @file
//! @SYMTestSuiteName		PBASE-F32-Sfsrv-PublicApi-ANY
//! @SYMScriptTestEnvironment	This test script requires a basic ANY.
/////////////////////////////////////////////////////////////////////
// PBASE-F32-Sfsrv-PublicApi-ANY.script
//
// Tests all public elements of the SfSrv class
// as a means of confidence that the APIs work as expected.
// 
// The purpose is to provide a regression test suite of PublishedAll APIs for SfSrv.
// Negative testing is performed to confirm that correct errors are returned when incorrect parameters are given.
// The tests are fully automated.
/////////////////////////////////////////////////////////////////////

RUN_SCRIPT	${SYSDRIVE}\base\PBASE-F32-Parse-Inherited-PublicApi-ANY.script
RUN_SCRIPT	${SYSDRIVE}\base\PBASE-F32-Parse-PublicApi-ANY.script
RUN_SCRIPT	${SYSDRIVE}\base\PBASE-F32-ParsePtr-Inherited-PublicApi-ANY.script
RUN_SCRIPT	${SYSDRIVE}\base\PBASE-F32-ParsePtr-PublicApi-ANY.script
RUN_SCRIPT	${SYSDRIVE}\base\PBASE-F32-ParsePtrC-Inherited-PublicApi-ANY.script
RUN_SCRIPT	${SYSDRIVE}\base\PBASE-F32-ParsePtrC-PublicApi-ANY.script
RUN_SCRIPT	${SYSDRIVE}\base\PBASE-F32-VolumeInfo-PublicApi-ANY.script
RUN_SCRIPT	${SYSDRIVE}\base\PBASE-F32-DriveUnit-PublicApi-ANY.script
RUN_SCRIPT	${SYSDRIVE}\base\pbase-f32-rfs-mounts-publicapi-any.script
RUN_SCRIPT	${SYSDRIVE}\base\pbase-f32-rfs-drives-publicapi-any.script
RUN_SCRIPT	${SYSDRIVE}\base\pbase-f32-rfs-files-publicapi-any.script
RUN_SCRIPT	${SYSDRIVE}\base\pbase-f32-rfs-misc-publicapi-any.script
